### PR TITLE
Standardize logging use, don't use StreamHandler

### PR DESCRIPTION
**Pull request by jjlawren**
The existing logging causes debug messages to be printed to stderr by use of a default `logging.StreamHandler()`. This PR standardizes how logging is instantiated across the library and removes the console output.

### CODE REVIEW

**Comment by JeffLIrion** [comment]
@Swind could you please review this when you get a chance. The Home Assistant Android TV integration uses this component, and users have reported that it spams the log.

**Comment by Swind** [comment]
Hi @jjlawren  and @JeffLIrion  

Sorry for the late reply.

Because sometimes I change the logging library or the format for debugging, so I use a helper function to generate the logger.

So I can't accept this pull request.

And I have some question, the message 

```
24-06-2019:13:10:37,589 DEBUG    [connection.py:47] Connection closed...
24-06-2019:13:10:48,16 DEBUG    [connection.py:24] Connect to adb server - 10.0.0.8:5037
24-06-2019:13:10:48,25 DEBUG    [connection.py:24] Connect to adb server - 10.0.0.8:5037
24-06-2019:13:10:48,28 DEBUG    [connection.py:75] b'001Dhost:transport:10.0.0.26:5555'
24-06-2019:13:10:48,29 DEBUG    [connection.py:75] b"0139shell:dumpsys power | grep 'Display Power' | grep -q 'state=ON' && echo -e '1\\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\\c' && dumpsys power | grep Locks | grep 'size=' && (dumpsys media_session | grep -m 1 'state=PlaybackState {' || echo) && dumpsys window windows | grep mCurrentFocus"
24-06-2019:13:10:48,75 DEBUG    [connection.py:47] Connection closed...
24-06-2019:13:10:48,77 DEBUG    [connection.py:24] Connect to adb server - 10.0.0.8:5037
24-06-2019:13:10:48,77 DEBUG    [connection.py:24] Connect to adb server - 10.0.0.8:5037
24-06-2019:13:10:48,79 DEBUG    [connection.py:75] b'001Dhost:transport:10.0.0.25:5555'
```

is `debug message`.

This message is only shown when you set the logging level to `DEBUG`. 
And even if you set the log level of the root logger to `DEBUG`, you still can use 

```python
logger = logging.getLogger('adb')
logger.setLevel(logging.ERROR)
```
to disable the debug message of this package.


test code

*with debug message*

```python
from adb.client import Client
import logging

root_logger = logging.getLogger()
root_logger.setLevel(logging.DEBUG)

client = Client()
client.devices()
```

message

```
26-06-2019:15:41:52,60 DEBUG    [connection.py:24] Connect to adb server - 127.0.0.1:5037
26-06-2019:15:41:52,61 DEBUG    [connection.py:75] b'000Chost:devices'
26-06-2019:15:41:52,61 DEBUG    [connection.py:47] Connection closed...
```

*without debug message*

```python
from adb.client import Client
import logging

root_logger = logging.getLogger()
root_logger.setLevel(logging.DEBUG)

adb_logger = logging.getLogger("adb")
adb_logger.setLevel(logging.CRITICAL)

client = Client()
client.devices()
```

message
```
```

So I think the root cause of the debug message isn't the StreamHandler.
The root cause is someone set the level of root logger to 'DEBUG' or 'NOTSET', but forget to set the logger of this package to the CRITICAL, WARNING or INFO. 

like this

https://github.com/home-assistant/home-assistant/blob/59ce31f44fbf6ee81e2eae5e6d639a814619f42a/homeassistant/bootstrap.py#L187

But I will modify the `get_logger` function, remove the StreamHandler and set the logger of this package to CRITICAL.

Is this helpful to you ?

**Comment by JeffLIrion** [comment]
> ```python
> adb_logger = logging.getLogger("adb")
> adb_logger.setLevel(logging.CRITICAL)
> ```

@Swind thanks for the detailed reply!  I'll give this approach a shot and see if it resolves the issue.

**Comment by jjlawren** [comment]
> But I will modify the get_logger function, remove the StreamHandler and set the logger of this package to CRITICAL.
> 
> Is this helpful to you ?

Yep, that would resolve the issues we've been seeing without requiring changes to how the library is currently used. Thanks!

**Pull request closed without merging**
