### PR TITLE
Implement async functionality

### PR DESCRIPTION
**Pull request by JeffLIrion**
The code in this pull request has 100% test coverage.

```
$ coverage run --source ppadb -m unittest discover -s test_async/ -t . && coverage report -m | grep async
...............
----------------------------------------------------------------------
Ran 15 tests in 0.029s

OK
ppadb/client_async.py                             15      0   100%
ppadb/command/host_async/__init__.py              19      0   100%
ppadb/command/transport_async/__init__.py         29      0   100%
ppadb/connection_async.py                         68      0   100%
ppadb/device_async.py                             37      0   100%
ppadb/sync_async/__init__.py                      68      0   100%
```

### CODE REVIEW

**Comment by JeffLIrion** [comment]
This would close https://github.com/Swind/pure-python-adb/issues/43

**Comment by JeffLIrion** [comment]
I've tested this, it works. Is there anything I can do to push this along?

**Comment by JeffLIrion** [comment]
Could I please get some feedback on this pull request. I want to use this code in my `androidtv` package, but for the time being I've had to resort to wrapping the sync pure-python-adb commands with `asyncio.get_current_loop().run_in_executor`. 

https://github.com/JeffLIrion/python-androidtv/blob/38a495e7b3197981ff3ca3a102b246f4bb056f8c/androidtv/adb_manager/adb_manager_async.py#L16-L54

**Comment by JeffLIrion** [comment]
FYI, this pull request preserves the sync functionality and backwards compatibility of this package. I only modified one existing file in this repo -- `setup.py` -- and the change I made won't break anything. All of the async code is in new files, so it won't impact the existing sync code in any way. And doing `pip install pure-python-adb` still requires no third party packages to be installed. 

Also, the async code works exactly the same as the sync code, the only difference being that all I/O is done using async functions. 

And again, I've tested this code and it works.

**Comment by Swind** [comment]
Hi @JeffLIrion 

Sorry for the late reply, 
I didn't receive the notification email about this pull request.
Thanks for your pull request !

**Pull request merged**
